projectGetById:
    get:
      tags:
        - Project
      summary: Retourne le projet par son ID
      operationId: getProject
      parameters:
        - name: idProject
          in: path
          description: ID du projet
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/ProjectDto.yaml#/ProjectDto'
        '400':
          $ref: '../common/common-responses.yaml#/components/responses/400'
        '403':
          $ref: '../common/common-responses.yaml#/components/responses/403'
        '404':
          $ref: '../common/common-responses.yaml#/components/responses/404'
        '500':
          $ref: '../common/common-responses.yaml#/components/responses/500'

projectGetAll:
  get:
    tags:
      - Project
    summary: Retourne tous les projets
    operationId: getAllProject
    responses:
      '200':
        description: SUCCESS
        content:
          'application/json':
            schema:
              $ref: '../model/ProjectDto.yaml#/ProjectList'
      '400':
        $ref: '../common/common-responses.yaml#/components/responses/400'
      '403':
        $ref: '../common/common-responses.yaml#/components/responses/403'
      '404':
        $ref: '../common/common-responses.yaml#/components/responses/404'
      '500':
        $ref: '../common/common-responses.yaml#/components/responses/500'

projectAdd:
  post:
    tags:
      - Project
    summary: Ajoute un projet à la bdd
    operationId: addProject
    requestBody:
      content:
        application/json:
          schema:
            $ref: '../model/ProjectDto.yaml#/ProjectDto'
    responses:
      '200':
        description: SUCCESS
        content:
          'application/json':
            schema:
              $ref: '../model/ProjectDto.yaml#/ProjectDto'
      '400':
        $ref: '../common/common-responses.yaml#/components/responses/400'
      '403':
        $ref: '../common/common-responses.yaml#/components/responses/403'
      '404':
        $ref: '../common/common-responses.yaml#/components/responses/404'
      '500':
        $ref: '../common/common-responses.yaml#/components/responses/500'

projectUpdate:
  put:
    tags:
      - Project
    summary: Modifie un projet
    operationId: updateProject
    parameters:
      - name: idProject
        in: path
        description: ID du projet
        required: true
        schema:
          type: integer
          format: int64
    requestBody:
      content:
        application/json:
          schema:
            $ref: '../model/ProjectDto.yaml#/ProjectDto'
    responses:
      '200':
        description: SUCCESS
        content:
          'application/json':
            schema:
              $ref: '../model/ProjectDto.yaml#/ProjectDto'
      '400':
        $ref: '../common/common-responses.yaml#/components/responses/400'
      '403':
        $ref: '../common/common-responses.yaml#/components/responses/403'
      '404':
        $ref: '../common/common-responses.yaml#/components/responses/404'
      '500':
        $ref: '../common/common-responses.yaml#/components/responses/500'
  
projectDeleteById:
  delete:
    tags:
      - Project
    summary: Supprime le projet par son ID
    operationId: deleteProject
    parameters:
      - name: idProject
        in: path
        description: ID du projet
        required: true
        schema:
          type: integer
          format: int64
    responses:
      '200':
        description: SUCCESS
        content:
          'application/json':
            schema:
              $ref: '../model/ResultDto.yaml#/ResultDto'
      '400':
        $ref: '../common/common-responses.yaml#/components/responses/400'
      '403':
        $ref: '../common/common-responses.yaml#/components/responses/403'
      '404':
        $ref: '../common/common-responses.yaml#/components/responses/404'
      '500':
        $ref: '../common/common-responses.yaml#/components/responses/500'