openapi: 3.0.3

info:
  title: API Alpha
  version: "1.0"
  description: Génération des endpoints de Alpha

servers:
  - url: "http://@api.host@:@api.port@/alpha-web"

paths:

################# Project API #################
  /project/get/{idProject}:
    $ref: './components/api/project.yaml#/projectGetById'

  /projects/get:
    $ref: './components/api/project.yaml#/projectGetAll'

  /project/post:
    $ref: './components/api/project.yaml#/projectAdd'

  /project/post/withImageIllustration:
    $ref: './components/api/project.yaml#/projectAddWithImageIllustration'

  /project/put/{idProject}:
    $ref: './components/api/project.yaml#/projectUpdate'

  /project/delete/{idProject}:
    $ref: './components/api/project.yaml#/projectDeleteById'

################# Tag API #################
  /tag/get/{idTag}:
    $ref: './components/api/tag.yaml#/tagGetById'

  /tags/get:
    $ref: './components/api/tag.yaml#/tagGetAll'

  /tag/post:
    $ref: './components/api/tag.yaml#/tagAdd'

  /tag/put/{idTag}:
    $ref: './components/api/tag.yaml#/tagUpdate'

  /tag/delete/{idTag}:
    $ref: './components/api/tag.yaml#/tagDeleteById'

################# ImageIllustration API #################
  /imageIllustration/get/{idImageIllustration}:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationGetById'

  /imageIllustration/get/byProject/{idProject}:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationGetByIdProject'

  /imageIllustrations/get:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationGetAll'

  /imageIllustration/post:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationAdd'

  /imageIllustration/put/{idImageIllustration}:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationUpdate'

  /imageIllustration/delete/{idImageIllustration}:
    $ref: './components/api/imageIllustration.yaml#/imageIllustrationDeleteById'

################# ImageProject API #################
  /imageProject/get/{idImageProject}:
    $ref: './components/api/imageProject.yaml#/imageProjectGetById'

  /imageProjects/get/{idProject}:
    $ref: './components/api/imageProject.yaml#/imageProjectGetAllByIdProject'

  /imageProjects/get:
    $ref: './components/api/imageProject.yaml#/imageProjectGetAll'

  /imageProject/post:
    $ref: './components/api/imageProject.yaml#/imageProjectAdd'

  /imageProject/post/all:
    $ref: './components/api/imageProject.yaml#/imageProjectAddMany'

  /imageProject/put/{idImageProject}:
    $ref: './components/api/imageProject.yaml#/imageProjectUpdate'

  /imageProject/delete/{idImageProject}:
    $ref: './components/api/imageProject.yaml#/imageProjectDeleteById'

################# Authenticate API #################

  /authenticate:
    $ref: './components/api/authentification.yaml#/Authenticate'